spring:
  datasource:
    url: jdbc:postgresql://172.31.61.148:5432/postgresql
    username: postgresql
    password: postgrespassword
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  rabbitmq:
    host: 172.31.26.227
    username: guest
    password: guest
    port: 5672